### ISSUE TITLE
0121 - Best Time to Buy and Sell Stock

### ISSUE THREAD

**Issue by amoghrajesh** [vJechsmayr/PythonAlgorithms#291]
## Description of the Problem
Say you have an array for which the ith element is the price of a given stock on day i.

If you were only permitted to complete at most one transaction (i.e., buy one and sell one share of the stock), design an algorithm to find the maximum profit.

Note that you cannot sell a stock before you buy one.

## Code
```
Example 1
Input: [7,1,5,3,6,4]
Output: 5
Explanation: Buy on day 2 (price = 1) and sell on day 5 (price = 6), profit = 6-1 = 5.
             Not 7-1 = 6, as selling price needs to be larger than buying price.
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/best-time-to-buy-and-sell-stock/)

**Comment by amoghrajesh** [comment]
Please assign this issue to me @vJechsmayr

**Comment by rajapuranam** [comment]
Can you please assign this issue to me. @vJechsmayr

**Comment by stoicfeats** [comment]
hey, @rajapuranam can you please help me with linking the pull requests to issues, I'm having troubles in linking my PR to issues.

**Comment by amoghrajesh** [comment]
Hey @rajapuranam, it is not an open issue. Please don't submit a solution unless you are assigned to it :(

**Comment by rajapuranam** [comment]
hi @amoghrajesh It is showing an open issue #291 in issues tab.

**Comment by rajapuranam** [comment]
@busybee23 I don't know how exactly my pull requests are linked to issues.

**Comment by amoghrajesh** [comment]
@rajapuranam looks like only ones assigned can get to PR. And the readme says that only the issue raiser will get the assignment

**Comment by rajapuranam** [comment]
@amoghrajesh So now, If I want to contribute, then what I have to do exactly?? Should I open a new issue and ask for the assignment? Or should I take the already open issues??

**Comment by vJechsmayr** [comment]
@rajapuranam When there is an Issue I created an noone is assigned (and no one commentend to assign) the you can comment so I assign you as soon as I'm online. 
When there is no free Issue and you want to work on an LeetCode Problem that is not already solved (See Problemnumbers in `Code/LeetCode` if your wished Problem is not already solved & at the Open Issues if not already someone else created an Issue for that Problem.
The Raiser of the Issue get the assignment prefered. So when someone creates an issue you don't have to comment to that issue because it's theirs. 😄 

Hope it's clear now. I have a full-time job so I cannot be online 24/7 so let me some hours sometimes to work through the PRs/Issues as soon as I have some minute sparetime.

**Comment by rajapuranam** [comment]
@vJechsmayr Ohh, Now I got clarity about this. Thank You so much for the clarification. 😊

**Comment by amoghrajesh** [comment]
Hey @vJechsmayr I am new to linking the issues to PR. Please let me know if I have linked it wrong

**Comment by stoicfeats** [comment]
> @busybee23 I don't know how exactly my pull requests are linked to issues.

@rajapuranam yes you have to first open an issue then link a PR to your issue created by yourself then @vJechsmayr will assign you and merge your work whenever she's online, make sure it's not spam because we make it really difficult for her to manage so many PRs.
